Repository AY2425S1-CS2103T-F10-2/tp, pull requests merged in 2024-11, with the labels that each got.

#197 Update UI to show at most 2 appointments per patient
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/ui/PatientCard.java
Labels: type.Task

#200 Change required fields for add and addf
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddFCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddFCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
Labels: type.Task, priority.High

#195 Fix ViewCommandTest
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/parser/AddFCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/AllergySorter.java
  src/main/java/seedu/address/model/patient/Allergy.java
  src/main/java/seedu/address/model/patient/AllergyList.java
  src/main/java/seedu/address/model/patient/ApptList.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/ui/PatientInfoPanel.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
Labels: priority.High

#202 Update HelpCommand windows
  src/main/java/seedu/address/logic/commands/BookApptCommand.java
  src/main/java/seedu/address/logic/commands/CommandKeywords.java
  src/main/java/seedu/address/ui/HelpKeywordWindow.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpKeywordWindow.fxml
Labels: type.Enchancement

#203 Add test cases for addf command
  src/main/java/seedu/address/model/patient/Patient.java
  src/test/java/seedu/address/logic/commands/AddFCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddFCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: type.Task, priority.High

#207 Update UI for home page
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/java/seedu/address/ui/PatientListPanel.java
  src/main/resources/view/PatientInfoPanel.fxml
  src/main/resources/view/PatientListCard.fxml
  src/main/resources/view/PatientListPanel.fxml
Labels: type.Task, priority.Medium

#209 Fix test cases
  src/main/java/seedu/address/logic/parser/AddFCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/test/data/JsonSerializableClinicConnectSystemTest/duplicatePatientClinicConnectSystem.json
  src/test/data/JsonSerializableClinicConnectSystemTest/typicalPatientsClinicConnectSystem.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/parser/AddFCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ClinicConnectSystemParserTest.java
  src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
  src/test/java/seedu/address/model/patient/PatientTest.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/PatientUtil.java
Labels: type.Task, type.Bug, priority.High

#212 Add HelpCommand testcases
  src/main/java/seedu/address/logic/commands/CommandKeywords.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
Labels: type.Task

#210 Create tests for filter command related files
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointmentdatefilter/AppointmentDateFilter.java
  src/main/java/seedu/address/model/filteredappointment/FilteredAppointment.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/ui/FilteredApptCard.java
  src/main/java/seedu/address/ui/FilteredApptListPanel.java
  src/main/java/seedu/address/ui/PatientListPanel.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddFCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/model/appointmentdatefilter/AppointmentDateFilterTest.java
  src/test/java/seedu/address/model/filteredappointment/FilteredAppointmentTest.java
  src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: type.Task

#219 Improve ViewCommand Ui
  src/main/java/seedu/address/ui/PatientInfoPanel.java
  src/main/resources/view/PatientInfoPanel.fxml
Labels: type.Enchancement, type.Task, priority.Medium

#214 Update appt commands to improve abstraction
  src/main/java/seedu/address/model/patient/ApptList.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/ui/PatientCard.java
Labels: type.Task, priority.Medium

#220 Update editcommand allergies
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/patient/AllergyList.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/patient/exceptions/AllergyAlreadyExistsException.java
  src/main/java/seedu/address/model/patient/exceptions/AllergyNotFoundException.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddFCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: type.Task

#222 Update EditCommand HelpKeywordWindow
  src/main/java/seedu/address/ui/HelpKeywordWindow.java
Labels: type.Enchancement

#228 Edit landing page file
  docs/index.md
Labels: type.Task, priority.Low

#233 Update ui to show healthservice for appt
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PatientListCard.fxml
Labels: type.Task

#231 Update ug
  docs/UserGuide.md
Labels: type.Task, priority.High

#260 Logging for addf command
  src/main/java/seedu/address/logic/commands/AddFCommand.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
Labels: type.Task

#261 Change filter command implementation
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/commandresult/CommandResult.java
  src/main/java/seedu/address/logic/commands/commandresult/DefaultCommandResult.java
  src/main/java/seedu/address/logic/commands/commandresult/ExitCommandResult.java
  src/main/java/seedu/address/logic/commands/commandresult/KeywordCommandResult.java
  src/main/java/seedu/address/logic/commands/commandresult/ShowFilteredApptsCommandResult.java
  src/main/java/seedu/address/logic/commands/commandresult/ShowPatientInfoCommandResult.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
Labels: alpha-bug

#262 Fix help window bug
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug, alpha-bug

#263 Fix display bug in help window
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug, alpha-bug

#264 Fix display bug for help message in help window
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug, alpha-bug

#266 Fix typo errors in UG
  .gitignore
  docs/UserGuide.md
Labels: type.Task

#267 Add logger statements
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/ui/FilteredApptListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PatientInfoPanel.java
Labels: priority.Low

#269 Branch add logger assertions
  src/main/java/seedu/address/logic/commands/BookApptCommand.java
  src/main/java/seedu/address/logic/commands/DeleteApptCommand.java
  src/main/java/seedu/address/logic/parser/BookApptCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteApptCommandParser.java
Labels: type.Task

#272 Fix bug in duplicate appointment handling
  src/main/java/seedu/address/model/patient/Appt.java
Labels: type.Bug, alpha-bug

#273 Fix bug errors in deleteapptcommand
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteApptCommand.java
  src/test/java/seedu/address/model/filteredappointment/FilteredAppointmentTest.java
Labels: type.Bug, alpha-bug

#274 Fix appointment field cutoff in viewUI
  src/main/resources/view/PatientInfoPanel.fxml
Labels: type.Task, priority.High

#276 Branch update book appt
  src/main/java/seedu/address/logic/commands/BookApptCommand.java
  src/main/java/seedu/address/model/patient/Appt.java
Labels: type.Bug, alpha-bug

#278 Change prefix "/" symbol to "|" symbol
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/Prefix.java
Labels: type.Task, priority.Medium

#279 Improve code quality
  docs/UserGuide.md
  docs/index.md
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/ui/PatientInfoPanel.java
  src/main/java/seedu/address/ui/PatientListPanel.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/patient/PatientTest.java
Labels: type.Enchancement, priority.Low

#281 Remove redundant error messages
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteApptCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: priority.Low

#284 Fix bug in local date time in bookappt
  src/main/java/seedu/address/logic/commands/BookApptCommand.java
Labels: type.Bug

#292 Code cleanup
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddFCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/parser/AddFCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/filteredappointment/FilteredAppointment.java
  src/main/java/seedu/address/model/healthservice/HealthService.java
  src/main/java/seedu/address/model/patient/Appt.java
  src/main/java/seedu/address/model/patient/ApptList.java
  src/main/java/seedu/address/storage/JsonAdaptedAppt.java
  src/main/java/seedu/address/storage/JsonAdaptedHealthService.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/commons/util/JsonUtilTest.java
  src/test/java/seedu/address/logic/commands/AddFCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPatientDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/model/filteredappointment/FilteredAppointmentTest.java
  src/test/java/seedu/address/model/patient/AllergyTest.java
  src/test/java/seedu/address/testutil/ClinicConnectSystemBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: type.Task, priority.High

#293 Fix healthrisk to allow lower case
  src/main/java/seedu/address/model/patient/HealthRisk.java
Labels: type.Bug, priority.Medium, alpha-bug

#296 Update UG with command symbol
  docs/UserGuide.md
Labels: type.Task, priority.High

#367 Fix formatting for code and remove list command
  docs/UserGuide.md
Labels: type.Task, priority.High

#368 Add formatting to legend
  docs/UserGuide.md
Labels: type.Task

#370 Update format of examples
  docs/UserGuide.md
Labels: type.Task, priority.High

#297 Clean unnecessary code
  src/main/java/seedu/address/model/patient/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/patient/NameContainsKeywordsPredicateTest.java
Labels: priority.Low

#372 Fix UG bugs
  docs/UserGuide.md
  docs/index.md
Labels: type.Bug

#377 Add test cases for bookappt and deleteappt commands and parsers
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/BookApptCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteApptCommandTest.java
  src/test/java/seedu/address/logic/parser/BookApptCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteApptCommandParserTest.java
Labels: type.Task

#373 Update bookappt to fix bugs on edge cases
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/appointmentdatefilter/AppointmentDateFilter.java
  src/main/java/seedu/address/model/patient/Appt.java
  src/main/java/seedu/address/model/patient/Birthdate.java
  src/main/java/seedu/address/storage/JsonAdaptedAppt.java
Labels: type.Bug

#383 Update add and addf command in ug
  docs/UserGuide.md
Labels: type.Task, priority.High

#385 Add table of contents and fix quick start
  docs/UserGuide.md
Labels: type.Task, priority.High

#388 Fix UG bugs for command descriptions
  docs/UserGuide.md
  docs/team/jolynleow2301.md
Labels: type.Bug

#403 FIx user guide
  docs/UserGuide.md
Labels: type.Task, priority.High

#404 Fix table of contents
  docs/UserGuide.md
Labels: type.Task, priority.High

#406 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Task

#414 Update Model architecture in DG
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PatientClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/PatientClassDiagram.png
  src/main/java/seedu/address/logic/commands/HomeCommand.java
Labels: type.Enchancement

#417 Add addf sequence diagram
  docs/diagrams/AddFSequenceDiagram.puml
  docs/images/AddFSequenceDiagram.png
Labels: type.Task, priority.High

#419 Add addf command for dg
  docs/DeveloperGuide.md
  docs/diagrams/AddFParseFieldsSequenceDiagram.puml
  docs/diagrams/AddFSequenceDiagram.puml
  docs/images/AddFParseFieldsSequenceDiagram.png
  docs/images/AddFSequenceDiagram.png
Labels: type.Task, priority.High

#420 Fix div issue
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#422 Update addf command for dg
  docs/DeveloperGuide.md
  docs/diagrams/AddFActivityDiagram.puml
  docs/diagrams/AddFSequenceDiagram.puml
  docs/images/AddFActivityDiagram.png
  docs/images/AddFSequenceDiagram.png
Labels: type.Task, priority.High

#424 Add class and activity diagrams for bookappt and deleteappt
  docs/diagrams/BookApptActivityDiagram.puml
  docs/diagrams/BookApptCommandClassDiagram.puml
  docs/diagrams/DeleteApptActivityDiagram.puml
  docs/diagrams/DeleteApptCommandClassDiagram.puml
Labels: type.Task

#427 Update DG for bookappt command
  docs/DeveloperGuide.md
Labels: type.Task

#432 Add mss for add a patient
  docs/DeveloperGuide.md
  docs/images/DeleteSequenceDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/ViewCommand.png
Labels: type.Task, priority.High
