Repository AY2425S1-CS2103T-F10-2/tp, pull requests merged in 2024-10, with the labels that each got.

#7 Add Jolyn's photo
  docs/images/jolynleow2301.png
Labels: type.Task

#12 Close #10 : Update AboutUs page with Cherng Yuen's info
  docs/AboutUs.md
  docs/team/arren11111.md
Labels: type.Task

#15 Update AboutUs page about Yugan's info
  docs/AboutUs.md
  docs/team/yugan01.md
Labels: type.Task

#16 Update AboutUs page with Jolyn's info
  docs/AboutUs.md
  docs/team/jolynleow.md
Labels: type.Task

#18 Add yuancheng's photo
  docs/images/yuanchengg.png
Labels: type.Task

#20 Update Yuan Cheng's AboutUs
  docs/AboutUs.md
  docs/team/yuanchengg.md
Labels: type.Task

#27 Update ReadMe.md
  README.md
  docs/images/Ui.png
Labels: type.Task, priority.High

#28 Add use cases to developer guide
  docs/DeveloperGuide.md
Labels: type.Task

#29 Update site wide settings
  docs/_config.yml
Labels: type.Task

#30 Update DG with target user profile, value propositions and user stories
  docs/DeveloperGuide.md
Labels: type.Task

#32 Add Glossary
  docs/DeveloperGuide.md
Labels: type.Task

#48 Add deleteCommand class
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.High

#49 Add new files for AddCommand
  src/main/java/seedu/address/model/healthservice/Healthservice.java
  src/main/java/seedu/address/model/person/Birthdate.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/Sex.java
Labels: type.Task

#43 Update HelpCommand format
  src/main/java/seedu/address/logic/commands/HelpCommand.java
Labels: priority.High

#41 Add optional patient fields
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Allergy.java
  src/main/java/seedu/address/model/person/BloodType.java
  src/main/java/seedu/address/model/person/HealthCondition.java
  src/main/java/seedu/address/model/person/HealthRecord.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/person/AllergyTest.java
Labels: type.Epic

#53 Updated Add command and Ui
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/healthservice/HealthService.java
  src/main/java/seedu/address/model/person/Birthdate.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedHealthService.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
Labels: type.Epic

#54 Update Help Command Window
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Task

#69 Branch addf command
  src/main/java/seedu/address/logic/commands/AddFCommand.java
  src/main/java/seedu/address/logic/commands/CommandKeywords.java
  src/main/java/seedu/address/logic/parser/AddFCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Allergy.java
  src/main/java/seedu/address/model/person/BloodType.java
  src/main/java/seedu/address/model/person/HealthRecord.java
  src/main/java/seedu/address/model/person/HealthRisk.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/model/person/AllergyTest.java
Labels: type.Epic

#72 Add validation checks
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/healthservice/HealthService.java
  src/main/java/seedu/address/model/person/Birthdate.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Sex.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: type.Task

#74 Update CommandResultTest
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
Labels: priority.High

#76 Update and add Tests for HelpCommand feature
  src/main/java/seedu/address/logic/parser/AddFCommandParser.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
Labels: priority.High

#78 Fix HelpCommand with keyword bug
  src/main/java/seedu/address/logic/commands/CommandKeywords.java
Labels: type.Bug

#85 Add test cases for optional fields
  src/main/java/seedu/address/logic/commands/AddFCommand.java
  src/main/java/seedu/address/logic/parser/AddFCommandParser.java
  src/main/java/seedu/address/ui/HelpKeywordWindow.java
  src/main/resources/view/HelpKeywordWindow.fxml
  src/test/java/seedu/address/logic/commands/AddFCommandTest.java
  src/test/java/seedu/address/model/person/AllergyTest.java
  src/test/java/seedu/address/model/person/BloodTypeTest.java
  src/test/java/seedu/address/model/person/HealthRecordTest.java
  src/test/java/seedu/address/model/person/HealthRiskTest.java
  src/test/java/seedu/address/model/person/NoteTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Epic

#91 Update appt command to include and save date and time
  src/main/java/seedu/address/logic/commands/ApptCommand.java
  src/main/java/seedu/address/logic/parser/AddFCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ApptCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Appt.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedAppt.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Epic

#93 Fix style errors
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#95 Update command details for HelpCommand Appt
  src/main/java/seedu/address/ui/HelpKeywordWindow.java
Labels: priority.High

#101 Edit ApptCommand feature to display text for no appointments
  src/main/java/seedu/address/logic/commands/ApptCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: type.Epic

#104 Add equals() method to HelpCommand
  src/main/java/seedu/address/logic/commands/HelpCommand.java
Labels: type.Task

#105 Update PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task

#97 Add ViewCommand.java, ViewCommandParser.java and make edits to Person.java to show patient de…
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
Labels: type.Task

#107 Update ApptCommand for duplicate handling
  src/main/java/seedu/address/logic/commands/ApptCommand.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: type.Task

#109 Fix test cases
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug

#116 Update Appt Command to sort appointment date and time
  src/main/java/seedu/address/logic/parser/ApptCommandParser.java
  src/main/java/seedu/address/model/ApptSorter.java
  src/main/java/seedu/address/model/person/Appt.java
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Task

#117 Add check argument functionality
  src/main/java/seedu/address/model/healthservice/HealthService.java
  src/main/java/seedu/address/model/person/Birthdate.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/Sex.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: type.Bug

#119 Add fixed healthservices to be provided
  src/main/java/seedu/address/model/healthservice/HealthService.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#114 Add EditCommand and EditComandParser
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddFCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Epic

#133 Branch view command
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Allergy.java
  src/main/java/seedu/address/model/person/Appt.java
  src/main/java/seedu/address/model/person/BloodType.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PatientInfoPanel.java
  src/main/resources/images/view_icon.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpKeywordWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PatientInfoPanel.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: type.Epic, priority.High

#138 Update EditCommandTest.java and EditCommandParserTest.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PatientInfoPanel.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#139 Add DeleteApptCommand feature
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteApptCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteApptCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Task, priority.High

#142 Remove repeated functions and fix checkstyle issues
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Appt.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/FilteredApptListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddFCommandTest.java
Labels: type.Bug

#148 Change allergies to a list
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddFCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/storage/JsonAdaptedAllergy.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/ui/PatientInfoPanel.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
Labels: type.Enchancement

#152 Add AddFCommand class diagram
  docs/diagrams/AddFCommand.puml
Labels: priority.High

#154 Add ApptList.java to improve on OOP
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddFCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/patient/AppointmentDateFilter.java
  src/main/java/seedu/address/model/patient/ApptList.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
Labels: type.Task, priority.High

#155 Change HealthRecord to ExistingCondition
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddFCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddFCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/patient/ExistingCondition.java
  src/main/java/seedu/address/model/patient/HealthRecord.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/ui/PatientInfoPanel.java
  src/main/resources/view/PatientInfoPanel.fxml
  src/test/data/JsonAddressBookStorageTest/invalidPatientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePatientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPatientsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/patient/ExistingConditionTest.java
  src/test/java/seedu/address/model/patient/HealthRecordTest.java
  src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: type.Enchancement

#162 Add uml diagram for ViewCommand
  docs/diagrams/ViewCommand.puml
Labels: type.Task, priority.Medium

#164 Add UML diagram for ApptCommand
  docs/diagrams/AddFCommand.puml
  docs/diagrams/ApptCommand.puml
Labels: type.Task, priority.Medium

#166 Fix broken ui and help command bug
  src/main/java/seedu/address/logic/commands/CommandKeywords.java
  src/main/java/seedu/address/model/patient/Patient.java
Labels: type.Bug, priority.High, severity.High

#173 Add resizable property to scrollpane for ViewCommand UI
  src/main/resources/view/PatientInfoPanel.fxml
Labels: type.Task, priority.Low

#171 Add error handling for ViewCommand
  src/main/java/seedu/address/logic/parser/AddFCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
Labels: type.Epic, type.Task, priority.High

#169 Add health service in ApptCommand
  src/main/java/seedu/address/logic/commands/ApptCommand.java
  src/main/java/seedu/address/logic/parser/ApptCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/healthservice/HealthService.java
  src/main/java/seedu/address/model/patient/Appt.java
  src/main/java/seedu/address/storage/JsonAdaptedAppt.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
Labels: type.Task, priority.High

#176 Update help command include new commands
  src/main/java/seedu/address/logic/commands/CommandKeywords.java
  src/main/java/seedu/address/ui/HelpKeywordWindow.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpKeywordWindow.css
  src/main/resources/view/HelpKeywordWindow.fxml
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Epic

#179 Update MESSAGE_USAGE for all commands
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddFCommand.java
  src/main/java/seedu/address/logic/commands/ApptCommand.java
  src/main/java/seedu/address/logic/commands/DeleteApptCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
Labels: type.Enchancement

#181 Change ListCommand to HomeCommand
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/HomeCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/HomeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task

#183 Change prefix existing conditions
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/ui/HelpKeywordWindow.java
Labels: type.Enchancement

#187 Allow keyboard shortcuts help window
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddFCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/ui/HelpKeywordWindow.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpKeywordWindow.css
Labels: type.Enchancement

#185 Add ViewCommand testcases
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
Labels: type.Task, priority.Medium

#192 Fix bug in ApptCommand
  src/main/java/seedu/address/logic/commands/ApptCommand.java
  src/main/java/seedu/address/logic/parser/DeleteApptCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/patient/Appt.java
  src/main/java/seedu/address/storage/JsonAdaptedAppt.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
Labels: type.Bug, priority.High

#194 Update bookappt and deleteappt commands
  src/main/java/seedu/address/logic/commands/BookApptCommand.java
  src/main/java/seedu/address/logic/commands/DeleteApptCommand.java
  src/main/java/seedu/address/logic/parser/BookApptCommandParser.java
  src/main/java/seedu/address/logic/parser/ClinicConnectSystemParser.java
  src/main/java/seedu/address/logic/parser/DeleteApptCommandParser.java
  src/main/java/seedu/address/model/patient/Appt.java
Labels: type.Task
